---
title: "Some final notes"
author: "Dr. Emmeke Aarts [e.aarts@uu.nl] <br> Pre-conference workshop for the International Conference on Multilevel Analysis "
date: "March 11, 2024"
output: 
  ioslides_presentation:
    css: style.css
    widescreen: true
    incremental: true
    logo: UU_logo_EN_CMYK.png
---


---

<div align="center">
<br>
<br>
<br>
<font size="10"> **Methodological notes **</font>
<br>
<br>
<br>
<br>
<font size="6"></font>
</div>

## How much data do we need? 

- Use multivariate data! 

- In case of categorical data, fixed (group-level parameters) only:
- Low complexity:  
    - 400 obs for 2 dep var on 5 subjects
    - 400 obs for 1 dep var in 30 subjects
- High complexity:
    - 800 obs for 4 dep var on 5 subjects
    - 1600 obs for 1 dep var on 30 subjects

More info: “Go multivariate: Recommendations on Bayesian multilevel HMMs with categorical data” in MBR, https://doi.org/10.1080/00273171/.2023.2205392


## Data preprocessing: do sanity checks! 

- Visualize your data 
- EMA / ESM data: check for response shifts, and omit data after shift takes place.  
    - Visualizations
    - Objective measures: e.g, very long or short response times and lack of variance in the responses over beeps 

---

<div align="center">
<br>
<br>
<br>
<font size="10"> **Statisticcal notes **</font>
<br>
<br>
<br>
<br>
<font size="6"></font>
</div>

## Homogeneous paramters over time

- A common assumption in HMMs is time-homogeneous parameters (also in `mHMMbayes`). 
- We assume that the process we are studying is generated by the same process over the observation time. 
- Sometimes, obvious we will violate this, for example when starting a study when patients are starting treatment. 
- Solution: include time-varying covaraites. Not implemented in CRAN verson of `mHMMbayes`, but I do have versions for this. 

## Starting values

- Can push the model more in a certain direction compared to weakly informative priors. 
- Reason: inform the first run of the forward-backward algorithm. 
- Use sensible starting values and do convergence checks. 
- When unclear what 'sensible' starting values are: obtain paramters when using a frequentist complete pooled approach, for example using the R package `depmixS4`. 

---

<div align="center">
<br>
<br>
<br>
<font size="10"> **Questions?**</font>
<br>
<br>
<br>
<br>
<font size="6"></font>
</div>